import asyncio
import typing as t
from enum import Enum
from typing import Self
from abc import abstractmethod, ABC

from core_lib.plugin import PluginsBearer, Plugin
from core_lib.event import Event

from desk_assistance import exc
from desk_assistance.config import AppConfig


class App(PluginsBearer["AppPlugin"]):
    def __init__(self, *, config: AppConfig | None = None):
        super().__init__()

        self._config: AppConfig = config or AppConfig()
        self._run_lock = asyncio.Lock()

    @property
    def running(self):
        return self._run_lock.locked()

    @property
    def config(self) -> AppConfig:
        return self._config

    @classmethod
    def create(cls, *, config: AppConfig) -> Self:
        app = cls(config=config)

        # TODO: Load plugins
        plugins = []

        for plugin in plugins or []:
            app.register(plugin)

        return app

    async def run(self):
        if not self.context_entered:
            raise exc.MissingContext(
                f"You are unable to run {self} for now. Please ensure context "
                f"when dealing with {self.__class__.__name__} context "
                f"dependent methods."
            )
        if self.running:
            raise exc.AppAlreadyRunning(
                f"You are unable to run {self} for now. It's already running. "
                f"{self.__class__.__name__} instance can only be ran once at "
                f"the time."
            )

        async with self._run_lock:
            await self.trigger(AppRunEvent())

            ...

            await self.trigger(AppCloseEvent())


class AppEventHandler(t.Protocol):
    @abstractmethod
    async def on_app_run(self):
        ...

    @abstractmethod
    async def on_app_close(self):
        ...


class AppEventType(str, Enum):
    APP_RUN = "APP_RUN"
    APP_CLOSE = "APP_CLOSE"


class AppPlugin(Plugin[App], AppEventHandler, ABC):
    """
    Plugin applicable to App instance
    """


class AppEvent(Event[AppPlugin]):
    """
    Event generated by App instance
    """

    EVENT_TYPE: AppEventType


class AppRunEvent(AppEvent):
    """
    Event generated on App run
    """

    EVENT_TYPE: t.Literal[AppEventType.APP_RUN] = AppEventType.APP_RUN


class AppCloseEvent(AppEvent):
    """
    Event generated on App close
    """

    EVENT_TYPE: t.Literal[AppEventType.APP_CLOSE] = AppEventType.APP_CLOSE
